"""Board C++ code emitter.

Generates ``board.hpp``, ``board.cpp``, and optionally ``board_uart.hpp``
from a parsed ``board.json`` manifest dict.

Unlike the device emitters these functions do NOT take a
``CanonicalDevice``/``SynthesisedDevice`` pair — the board manifest is
the sole source of truth.

Public surface
--------------
* :func:`emit_board_hpp`  — public interface header
* :func:`emit_board_cpp`  — runtime implementation + ISR handlers
* :func:`emit_board_uart_hpp` — UART connector types (when ``uart.debug`` present)
"""

from __future__ import annotations

import re
from typing import Any


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _system_clock_hz(manifest: dict[str, Any]) -> int:
    """Best-effort Hz from ``clock_profiles``, falling back to family default."""
    for profile in manifest.get("clock_profiles", []):
        m = re.search(r"(\d+)mhz", profile, re.IGNORECASE)
        if m:
            return int(m.group(1)) * 1_000_000
    _defaults: dict[str, int] = {
        "stm32g0": 64_000_000,
        "stm32g4": 170_000_000,
        "stm32f4": 84_000_000,
        "stm32f1": 72_000_000,
        "stm32h7": 480_000_000,
        "stm32l4": 80_000_000,
        "stm32l5": 110_000_000,
        "stm32u5": 160_000_000,
    }
    return _defaults.get(manifest.get("family", ""), 16_000_000)


def _pin_id(pin: str) -> str:
    """``"PA5"`` → ``"alloy::device::PinId::PA5"``."""
    return f"alloy::device::PinId::{pin}"


def _peripheral_id(name: str) -> str:
    """``"USART2"`` → ``"alloy::device::PeripheralId::USART2"``."""
    return f"alloy::device::PeripheralId::{name}"


def _signal_id(name: str) -> str:
    return f"alloy::device::SignalId::{name}"


def _off_state(active_high: bool) -> str:
    """GPIO initial state = OFF (before explicit on/off call)."""
    return "alloy::hal::PinState::Low" if active_high else "alloy::hal::PinState::High"


def _gen_header(display: str, board_id: str, filename: str) -> list[str]:
    return [
        f"// Generated by alloy-codegen — DO NOT EDIT",
        f"// Board : {display}",
        f"// Source: boards/{board_id}/board.json",
        f"",
    ]


# ---------------------------------------------------------------------------
# emit_board_hpp
# ---------------------------------------------------------------------------

def emit_board_hpp(manifest: dict[str, Any]) -> str:
    """Render the public board interface header.

    Emits ``namespace board`` with:
    * Clock constants (via ``device::system_clock::ProfileTraits`` when
      available, hardcoded fallback otherwise).
    * ``BoardSysTick`` / ``RTOSTick`` type aliases.
    * ``namespace led`` declarations for every LED entry in the manifest.
    * ``namespace button`` declarations for every button entry.
    * ``board::init()`` declaration.
    """
    board_id: str = manifest["board_id"]
    display: str = manifest.get("display_name", board_id)
    leds: list[dict[str, Any]] = manifest.get("leds", [])
    buttons: list[dict[str, Any]] = manifest.get("buttons", [])
    clock_profiles: list[str] = manifest.get("clock_profiles", [])
    fallback_hz: int = _system_clock_hz(manifest)

    L: list[str] = _gen_header(display, board_id, "board.hpp")
    L += [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "#include \"device/system_clock.hpp\"",
        "#include \"hal/systick.hpp\"",
        "",
        "namespace board {",
        "",
        "// ── Clock ──────────────────────────────────────────────────────────────────",
    ]

    if clock_profiles:
        profile_id = clock_profiles[0]   # e.g. "default_pll_64mhz"
        L += [
            "#if ALLOY_DEVICE_SYSTEM_CLOCK_AVAILABLE",
            "namespace detail {",
            f"static constexpr auto kClockProfile =",
            f"    alloy::device::system_clock::ProfileId::{profile_id};",
            f"using ClockProfileTraits =",
            f"    alloy::device::system_clock::ProfileTraits<kClockProfile>;",
            f"static_assert(ClockProfileTraits::kPresent,",
            f"    \"Clock profile '{profile_id}' not present in device contract\");",
            "}  // namespace detail",
            "inline constexpr std::uint32_t kSystemClockHz = detail::ClockProfileTraits::kSysclkHz;",
            "inline constexpr std::uint32_t kApbClockHz    = detail::ClockProfileTraits::kPclkHz;",
            "#else",
            f"// Fallback: derived from clock profile name \"{profile_id}\"",
            f"inline constexpr std::uint32_t kSystemClockHz = {fallback_hz}u;",
            f"inline constexpr std::uint32_t kApbClockHz    = {fallback_hz}u;",
            "#endif",
            "",
        ]
    else:
        L += [
            f"inline constexpr std::uint32_t kSystemClockHz = {fallback_hz}u;",
            f"inline constexpr std::uint32_t kApbClockHz    = {fallback_hz}u;",
            "",
        ]

    L += [
        "// ── Timing ─────────────────────────────────────────────────────────────────",
        "using BoardSysTick = alloy::hal::cortex_m::SysTick<kSystemClockHz>;",
        "using RTOSTick     = BoardSysTick;",
        "",
    ]

    # LED declarations
    if leds:
        L.append("// ── LED ────────────────────────────────────────────────────────────────────")
        primary = leds[0]
        _active_low: bool = bool(primary.get("active_low", False))
        active_high: bool = bool(primary.get("active_high", not _active_low))
        L += [
            "namespace led {",
            f"inline constexpr bool kActiveHigh = {'true' if active_high else 'false'};",
            "void init();",
            "void on();",
            "void off();",
            "void toggle();",
            "}  // namespace led",
            "",
        ]

    # Button declarations
    if buttons:
        L.append("// ── Buttons ────────────────────────────────────────────────────────────────")
        for btn in buttons:
            name: str = btn["name"]
            active_low: bool = bool(btn.get("active_low", False))
            L += [
                f"namespace {name} {{",
                f"inline constexpr bool kActiveLow = {'true' if active_low else 'false'};",
                f"[[nodiscard]] bool is_pressed();",
                f"}}  // namespace {name}",
            ]
        L.append("")

    L += [
        "// ── Initialisation ─────────────────────────────────────────────────────────",
        "void init();",
        "",
        "}  // namespace board",
        "",
    ]

    return "\n".join(L)


# ---------------------------------------------------------------------------
# emit_board_cpp
# ---------------------------------------------------------------------------

def emit_board_cpp(manifest: dict[str, Any]) -> str:
    """Render the board runtime implementation.

    Emits:
    * Static GPIO handle accessors for every LED / button.
    * ``board::led::init/on/off/toggle`` for the first (primary) LED.
    * ``board::{name}::is_pressed()`` for every button.
    * ``board::init()`` — clock → SysTick → peripherals → enable IRQ.
    * ``SysTick_Handler`` ISR (ARM Cortex-M).
    """
    board_id: str = manifest["board_id"]
    display: str = manifest.get("display_name", board_id)
    leds: list[dict[str, Any]] = manifest.get("leds", [])
    buttons: list[dict[str, Any]] = manifest.get("buttons", [])

    L: list[str] = _gen_header(display, board_id, "board.cpp")
    L += [
        "#include \"board.hpp\"",
        "",
        "#include <cstdint>",
        "",
        "#include \"hal/gpio.hpp\"",
        "#include \"device/clock_config.hpp\"",
        "#include \"device/system_clock.hpp\"",
        "",
        "using namespace alloy::hal;",
        "",
        "namespace board {",
        "namespace {",
        "",
    ]

    # ── LED handles ─────────────────────────────────────────────────────────
    for led in leds:
        pin: str = led["pin"]
        name: str = led["name"]
        _al: bool = bool(led.get("active_low", False))
        active_high: bool = bool(led.get("active_high", not _al))
        off_st: str = _off_state(active_high)
        L += [
            f"// LED {name} — {pin} (active {'high' if active_high else 'low'})",
            f"using Led_{name} = alloy::device::pin<{_pin_id(pin)}>;",
            f"auto& led_{name}_handle() {{",
            f"    static auto handle = alloy::hal::gpio::open<Led_{name}>({{",
            f"        .direction     = PinDirection::Output,",
            f"        .drive         = PinDrive::PushPull,",
            f"        .pull          = PinPull::None,",
            f"        .initial_state = {off_st},",
            f"    }});",
            f"    return handle;",
            f"}}",
            f"",
        ]

    # ── Button handles ───────────────────────────────────────────────────────
    for btn in buttons:
        pin = btn["pin"]
        name = btn["name"]
        L += [
            f"// Button {name} — {pin}",
            f"using Button_{name} = alloy::device::pin<{_pin_id(pin)}>;",
            f"auto& button_{name}_handle() {{",
            f"    static auto handle = alloy::hal::gpio::open<Button_{name}>({{",
            f"        .direction = PinDirection::Input,",
            f"        .pull      = PinPull::PullUp,",
            f"    }});",
            f"    return handle;",
            f"}}",
            f"",
        ]

    # ── Init state + clock helper ────────────────────────────────────────────
    clock_profiles_cpp: list[str] = manifest.get("clock_profiles", [])
    L.append("static bool board_initialized = false;")
    L.append("")
    L.append("inline void configure_system_clock() {")
    if clock_profiles_cpp:
        # Use the first declared profile so hardware runs at the intended frequency.
        # apply_default() silently falls back to the safe/slow internal oscillator
        # which is NOT what board.json's clock_profiles entry describes.
        p = clock_profiles_cpp[0]
        L += [
            "#if ALLOY_DEVICE_CLOCK_CONFIG_AVAILABLE",
            f"    static_cast<void>(alloy::device::clock_config::apply_profile<alloy::device::clock_config::ProfileId::{p}>());",
            "#elif ALLOY_DEVICE_SYSTEM_CLOCK_AVAILABLE",
            f"    static_cast<void>(alloy::device::system_clock::apply_profile<alloy::device::system_clock::ProfileId::{p}>());",
            "#endif",
        ]
    else:
        L += [
            "#if ALLOY_DEVICE_CLOCK_CONFIG_AVAILABLE",
            "    static_cast<void>(alloy::device::clock_config::apply_default());",
            "#elif ALLOY_DEVICE_SYSTEM_CLOCK_AVAILABLE",
            "    static_cast<void>(alloy::device::system_clock::apply_default());",
            "#endif",
        ]
    L += [
        "}",
        "",
        "}  // namespace",
        "",
    ]

    # ── LED implementations (primary = first LED) ────────────────────────────
    if leds:
        primary = leds[0]
        pname: str = primary["name"]
        _al2: bool = bool(primary.get("active_low", False))
        active_high = bool(primary.get("active_high", not _al2))
        L += [
            "namespace led {",
            "",
            "void init() {",
            f"    led_{pname}_handle().configure().unwrap();",
            "    off();",
            "}",
            "",
            "void on() {",
            "    if constexpr (kActiveHigh) {",
            f"        led_{pname}_handle().set_high().unwrap();",
            "    } else {",
            f"        led_{pname}_handle().set_low().unwrap();",
            "    }",
            "}",
            "",
            "void off() {",
            "    if constexpr (kActiveHigh) {",
            f"        led_{pname}_handle().set_low().unwrap();",
            "    } else {",
            f"        led_{pname}_handle().set_high().unwrap();",
            "    }",
            "}",
            "",
            "void toggle() {",
            f"    led_{pname}_handle().toggle().unwrap();",
            "}",
            "",
            "}  // namespace led",
            "",
        ]

    # ── Button implementations ───────────────────────────────────────────────
    for btn in buttons:
        name = btn["name"]
        active_low: bool = bool(btn.get("active_low", False))
        pressed_state = "PinState::Low" if active_low else "PinState::High"
        L += [
            f"namespace {name} {{",
            "",
            "bool is_pressed() {",
            f"    button_{name}_handle().configure().unwrap();",
            f"    return button_{name}_handle().read().unwrap() == {pressed_state};",
            "}",
            "",
            f"}}  // namespace {name}",
            "",
        ]

    # ── board::init() ────────────────────────────────────────────────────────
    periph_inits: list[str] = []
    if leds:
        periph_inits.append("    led::init();")

    L += [
        "void init() {",
        "    if (board_initialized) { return; }",
        "    configure_system_clock();",
        "    alloy::hal::SysTickTimer::init_ms<BoardSysTick>(1);",
    ]
    L.extend(periph_inits)
    L += [
        "    __asm volatile(\"cpsie i\" ::: \"memory\");",
        "    board_initialized = true;",
        "}",
        "",
        "}  // namespace board",
        "",
        "// ── ISR handlers ───────────────────────────────────────────────────────────",
        "extern \"C\" void SysTick_Handler() {",
        "    board::BoardSysTick::increment_tick();",
        "#ifdef ALLOY_RTOS_ENABLED",
        "    alloy::rtos::RTOS::tick().unwrap();",
        "#endif",
        "}",
        "",
    ]

    return "\n".join(L)


# ---------------------------------------------------------------------------
# emit_board_uart_hpp
# ---------------------------------------------------------------------------

def emit_board_uart_hpp(manifest: dict[str, Any]) -> str:
    """Render UART connector type aliases from ``uart.debug`` manifest entry.

    Returns an empty string when no ``uart.debug`` section is present.
    """
    uart_debug: dict[str, Any] | None = manifest.get("uart", {}).get("debug")
    if not uart_debug:
        return ""

    board_id: str = manifest["board_id"]
    display: str = manifest.get("display_name", board_id)
    peripheral: str = uart_debug["peripheral"]
    tx_pin: str = uart_debug["tx"]
    rx_pin: str = uart_debug["rx"]
    baud: int = int(uart_debug.get("baud", 115200))

    L: list[str] = _gen_header(display, board_id, "board_uart.hpp")
    L += [
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "#include \"device/runtime.hpp\"",
        "#include \"hal/connect/connector.hpp\"",
        "#include \"hal/uart.hpp\"",
        "",
        "#include \"board.hpp\"",
        "",
        "namespace board {",
        "",
        f"// Debug UART: {peripheral} TX={tx_pin} RX={rx_pin} @ {baud} baud",
        f"using DebugUartConnector = alloy::hal::connection::connector<",
        f"    {_peripheral_id(peripheral)},",
        f"    alloy::hal::connection::tx<{_pin_id(tx_pin)}, {_signal_id('signal_tx')}>,",
        f"    alloy::hal::connection::rx<{_pin_id(rx_pin)}, {_signal_id('signal_rx')}>>;",
        f"using DebugUart = alloy::hal::uart::port<DebugUartConnector>;",
        "",
        f"inline constexpr std::uint32_t kDebugUartBaud = {baud}u;",
        f"inline constexpr std::uint32_t kDebugUartPeripheralClockHz = kApbClockHz;",
        "",
        "[[nodiscard]] inline auto make_debug_uart(",
        "    alloy::hal::uart::Config config = {}) -> DebugUart {",
        "    if (config.peripheral_clock_hz == 0u) {",
        "        config.peripheral_clock_hz = kDebugUartPeripheralClockHz;",
        "    }",
        "    return DebugUart{config};",
        "}",
        "",
        "}  // namespace board",
        "",
    ]

    return "\n".join(L)


__all__ = ["emit_board_cpp", "emit_board_hpp", "emit_board_uart_hpp"]
