"""Release metadata helpers for remote alloy-devices publication."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from alloy_codegen.errors import ReleaseMetadataError


@dataclass(frozen=True, slots=True)
class ReleaseMetadata:
    """Deterministic metadata for one remote publication commit."""

    source_revision: str
    scope_path: str
    target_repository: str
    target_artifact_revision: str
    commit_subject: str
    commit_body: str

    def to_dict(self) -> dict[str, str]:
        return {
            "source_revision": self.source_revision,
            "scope_path": self.scope_path,
            "target_repository": self.target_repository,
            "target_artifact_revision": self.target_artifact_revision,
            "commit_subject": self.commit_subject,
            "commit_body": self.commit_body,
        }


def build_release_metadata(
    *,
    publish_report: dict[str, Any],
    source_revision: str,
) -> ReleaseMetadata:
    """Build commit metadata from a successful publish report."""
    if publish_report.get("stage") != "publish":
        raise ReleaseMetadataError("Release metadata requires a publish-stage report.")
    if publish_report.get("status") != "completed":
        raise ReleaseMetadataError("Release metadata requires a completed publish report.")

    payload = _require_mapping(publish_report.get("payload"), "publish payload")
    scope_payload = payload.get("scope")
    if scope_payload is None:
        scope_payload = publish_report.get("scope")
    scope = _require_mapping(scope_payload, "publish scope")
    target_repository = _require_string(payload.get("target_repository"), "target_repository")
    target_artifact_revision = _require_string(
        payload.get("target_artifact_revision"),
        "target_artifact_revision",
    )
    scope_path = build_scope_path(scope)
    short_revision = source_revision[:12]
    commit_subject = (
        f"chore(devices): publish {scope_path} from alloy-codegen {short_revision}"
    )
    commit_body = "\n".join(
        [
            "Publish validated artifacts to alloy-devices.",
            "",
            f"Source revision: {source_revision}",
            f"Scope: {scope_path}",
            f"Target repository: {target_repository}",
            f"Target artifact revision: {target_artifact_revision}",
        ]
    )
    return ReleaseMetadata(
        source_revision=source_revision,
        scope_path=scope_path,
        target_repository=target_repository,
        target_artifact_revision=target_artifact_revision,
        commit_subject=commit_subject,
        commit_body=commit_body,
    )


def build_scope_path(scope: dict[str, Any]) -> str:
    """Build a deterministic publication path label from a scope payload."""
    vendor = _require_string(scope.get("vendor"), "scope.vendor")
    family = _require_string(scope.get("family"), "scope.family")
    device = scope.get("device")
    parts = [vendor, family]
    if device is not None:
        parts.append(_require_string(device, "scope.device"))
    return "/".join(parts)


def write_github_output(metadata: ReleaseMetadata, output_path: Path) -> None:
    """Write release metadata into a GitHub Actions output file."""
    delimiter = "ALLOY_CODEGEN_COMMIT_BODY"
    with output_path.open("a", encoding="utf-8") as handle:
        handle.write(f"scope_path={metadata.scope_path}\n")
        handle.write(f"target_repository={metadata.target_repository}\n")
        handle.write(f"target_artifact_revision={metadata.target_artifact_revision}\n")
        handle.write(f"commit_subject={metadata.commit_subject}\n")
        handle.write(f"commit_body<<{delimiter}\n")
        handle.write(metadata.commit_body)
        handle.write(f"\n{delimiter}\n")


def _require_mapping(value: Any, field_name: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ReleaseMetadataError(f"{field_name} must be a JSON object.")
    return value


def _require_string(value: Any, field_name: str) -> str:
    if not isinstance(value, str) or not value:
        raise ReleaseMetadataError(f"{field_name} must be a non-empty string.")
    return value


def build_parser() -> argparse.ArgumentParser:
    """Create the CLI parser for release metadata generation."""
    parser = argparse.ArgumentParser(
        prog="python -m alloy_codegen.release",
        description="Generate deterministic release metadata from a publish report.",
    )
    parser.add_argument(
        "--publish-report",
        required=True,
        help="Path to a machine-readable publish report generated by alloy-codegen.",
    )
    parser.add_argument(
        "--source-revision",
        required=True,
        help="Git revision of the alloy-codegen source that produced the report.",
    )
    parser.add_argument(
        "--github-output",
        default=None,
        help="Optional GitHub Actions output file to populate with commit metadata.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print the derived release metadata as JSON.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""
    parser = build_parser()
    args = parser.parse_args(argv)
    report = json.loads(Path(args.publish_report).read_text(encoding="utf-8"))
    metadata = build_release_metadata(
        publish_report=report,
        source_revision=args.source_revision,
    )
    if args.github_output is not None:
        write_github_output(metadata, Path(args.github_output))
    if args.json or args.github_output is None:
        print(json.dumps(metadata.to_dict(), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
