"""Auto-generated README for the alloy-devices publication root.

Renders a markdown table of every admitted ``(vendor, family)`` pair plus the
devices, packages, and peripherals each one carries.  After
``consume-alloy-devices-yml-as-canonical-input`` Phase 3 the emitter is a
pure function over the canonical YAMLs in the ``alloy-devices-yml``
submodule — no patches, no registry — so every parallel publish job
produces byte-identical output and the publication-diff step trivially
detects when the README really changed.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from alloy_codegen.bootstrap import DEVICE_REGISTRY
from alloy_codegen.context import ExecutionContext
from alloy_codegen.errors import StageExecutionError
from alloy_codegen.reporting import EmittedArtifact
from alloy_codegen.sources.alloy_devices_yml import load_canonical_device

# CMSIS / Cortex standard cores that ship in every ARM SVD.  Filtered out of
# the README peripheral list — these aren't user-facing peripherals, just the
# standard core debug/control blocks.
_CMSIS_STANDARD_PERIPHERALS: frozenset[str] = frozenset(
    {
        "CoreDebug",
        "DWT",
        "ETM",
        "FPB",
        "FPU",
        "ITM",
        "MPU",
        "NVIC",
        "SCB",
        "SCnSCB",
        "SysTick",
        "TPIU",
    }
)

README_PATH = "README.md"
README_ARTIFACT_KIND = "documentation"


# ---------------------------------------------------------------------------
# Internal data structures
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class _FamilyRow:
    vendor: str
    family: str
    isa: str
    devices: tuple[str, ...]
    packages: tuple[str, ...]
    peripherals: tuple[str, ...]


# ---------------------------------------------------------------------------
# ISA labels
# ---------------------------------------------------------------------------


_ISA_LABELS: dict[str, str] = {
    "cortex-m0plus": "Cortex-M0+",
    "cortex-m0plus-dual": "Cortex-M0+ (dual)",
    "cortex-m4": "Cortex-M4",
    "cortex-m4f": "Cortex-M4F",
    "cortex-m7": "Cortex-M7",
    "cortex-m7f": "Cortex-M7F",
    "rv32imc": "RISC-V RV32IMC",
    "rv32imac": "RISC-V RV32IMAC",
    "riscv": "RISC-V",
    "xtensa-lx6": "Xtensa LX6 (dual-core)",
    "xtensa-lx7": "Xtensa LX7 (dual-core)",
    "avr8": "AVR8",
}


def _isa_label(core: str) -> str:
    return _ISA_LABELS.get(core.lower(), core)


# ---------------------------------------------------------------------------
# Row construction (all data sourced from the canonical YAML)
# ---------------------------------------------------------------------------


def _row_for_family(
    *,
    vendor: str,
    family: str,
    devices: tuple[str, ...],
) -> _FamilyRow:
    if not devices:
        raise StageExecutionError(
            f"DEVICE_REGISTRY lists no devices for {vendor}/{family}; cannot render README row."
        )
    irs = [load_canonical_device(vendor=vendor, family=family, device=device) for device in devices]
    isa = _isa_label(irs[0].identity.core)
    packages = tuple(sorted({pkg.name for ir in irs for pkg in ir.packages}))
    peripherals = tuple(
        sorted(
            {
                peripheral.name
                for peripheral in irs[0].peripherals
                if peripheral.name not in _CMSIS_STANDARD_PERIPHERALS
            }
        )
    )
    return _FamilyRow(
        vendor=vendor,
        family=family,
        isa=isa,
        devices=devices,
        packages=packages,
        peripherals=peripherals,
    )


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def _render_header(alloy_codegen_revision: str | None) -> tuple[str, ...]:
    revision_text = alloy_codegen_revision or "(revision unknown)"
    return (
        "# alloy-devices",
        "",
        f"> Auto-generated by alloy-codegen `{revision_text}`. Do not edit manually — every"
        " publish run regenerates this file from the canonical YAMLs in `data/devices/`.",
        "",
    )


def _render_table(rows: tuple[_FamilyRow, ...]) -> tuple[str, ...]:
    lines: list[str] = [
        "## Admitted families",
        "",
        "| Vendor | Family | ISA | Devices | Packages | Peripherals |",
        "|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| {vendor} | {family} | {isa} | {devices} | {packages} | {peripherals} |".format(
                vendor=row.vendor,
                family=row.family,
                isa=row.isa,
                devices=", ".join(row.devices),
                packages=", ".join(row.packages),
                peripherals=", ".join(row.peripherals) if row.peripherals else "—",
            )
        )
    lines.append("")
    return tuple(lines)


def _render_markdown(rows: tuple[_FamilyRow, ...], *, alloy_codegen_revision: str | None) -> str:
    lines: list[str] = []
    lines.extend(_render_header(alloy_codegen_revision))
    lines.extend(_render_table(rows))
    if not lines or lines[-1] != "":
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_devices_readme(
    context: ExecutionContext,
    *,
    alloy_codegen_revision: str | None = None,
) -> str:
    """Render the alloy-devices README markdown for the current admitted set."""
    del context  # Unused — admission walks the YAML submodule directly.
    rows = tuple(
        _row_for_family(vendor=vendor, family=family, devices=devices)
        for (vendor, family), devices in sorted(DEVICE_REGISTRY.items())
    )
    return _render_markdown(rows, alloy_codegen_revision=alloy_codegen_revision)


def emit_devices_readme(
    context: ExecutionContext,
    *,
    alloy_codegen_revision: str | None = None,
) -> EmittedArtifact:
    """Emit the alloy-devices root README artifact.

    The emitter is deterministic: identical inputs produce byte-identical
    output across parallel publish jobs.  ``alloy_codegen_revision`` is
    informational only — it appears in the auto-generated header but does
    NOT influence the table content (so README regeneration on a no-op
    revision bump still no-ops the publish-diff check).
    """
    content = render_devices_readme(context, alloy_codegen_revision=alloy_codegen_revision)
    return EmittedArtifact(
        path=README_PATH,
        artifact_kind=README_ARTIFACT_KIND,
        content=content,
        content_sha256=hashlib.sha256(content.encode("utf-8")).hexdigest(),
        content_bytes=len(content.encode("utf-8")),
    )
