"""Per-device compile gate for the v2.1 alloy-codegen output.

Drives ``clang++`` over a generated probe TU for every admitted
device, proving that the emitted ``peripheral_traits.h`` /
``peripheral_id.hpp`` / ``rcc_traits.hpp`` / ``rcc_enable.hpp``
surface compiles cleanly.

Invocation::

    python scripts/run_compile_gate.py [--device <id>] [--ci]
                                       [--clang <path>] [--report-matrix]

Flags
-----

``--device <id>``
    Restrict the run to a single device (matches the third
    component of the ``vendor/family/device`` triple, e.g.
    ``stm32g0b1cbtx``).  Without this flag, every admitted device
    is gated.

``--ci``
    CI-friendly mode: enables ``-j$(os.cpu_count())`` parallelism
    and fails fast on the first compile error.  Default mode runs
    serial and continues on failure to surface every broken device
    per run.

``--report-only``
    Don't fail the script on compile errors; print the matrix and
    exit zero.  Used during the initial roll-out where only five
    reference fixtures are hard-fail and the rest are
    report-only.

``--clang <path>``
    Override the clang++ binary (default: ``clang++`` on PATH).

The generated probe TU references each peripheral's
``kBaseAddress`` and, when present, its ``kGateModel``.  Missing
namespaces, malformed constexpr lines, or mismatched enum values
all fail compile.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from alloy_codegen.bootstrap import DEVICE_REGISTRY  # noqa: E402
from alloy_codegen.cli import _EMITTERS  # noqa: E402
from alloy_codegen.sources.alloy_devices_yml import (  # noqa: E402
    load_with_synthesis,
)


# ---------------------------------------------------------------------------
# Reference fixtures — these are HARD-FAIL during the initial roll-out
# because they exercise every GateModel branch.  After
# ``complete-rcc-synthesis-cross-vendor`` archives, the remaining
# devices flip from report-only to hard-fail too.
# ---------------------------------------------------------------------------

REFERENCE_FIXTURES: tuple[tuple[str, str, str], ...] = (
    ("st", "stm32g0", "stm32g0b1cbtx"),
    ("raspberrypi", "rp2040", "rp2040"),
    ("nxp", "imxrt1060", "mimxrt1062"),
    ("microchip", "avr-da", "avr64da32"),
    ("espressif", "esp32c3", "esp32c3"),
)


# Compiler flags applied to the probe TU.  No ``-ffreestanding`` /
# ``-nostdlib`` because the probe is a ``-c`` step only — never
# linked.  The headers are pure ``constexpr`` and only pull in
# ``<cstddef>`` / ``<cstdint>``, both of which are core C++20.
PROBE_CFLAGS: tuple[str, ...] = (
    "-std=c++20",
    "-Wall",
    "-Werror",
    "-Wundef",
    "-Wno-unused-const-variable",  # constexpr probe sentinels intentional
    "-Wno-c++23-extensions",       # allow if-constexpr edge cases
    "-c",                          # compile only, never link
    "-o",
    os.devnull,
)


@dataclass(slots=True)
class GateResult:
    vendor: str
    family: str
    device: str
    status: str  # "pass" / "fail" / "skip"
    detail: str = ""

    @property
    def triple(self) -> str:
        return f"{self.vendor}/{self.family}/{self.device}"


# ---------------------------------------------------------------------------
# Probe TU generation
# ---------------------------------------------------------------------------


def _ns_name(vendor: str, family: str, device: str) -> str:
    """Mirror the same vendor/family/device → C++ namespace mapping
    that the emitters use.  Always rooted under ``alloy::``."""
    parts = ("alloy", vendor, family, device)
    return "::".join(p.replace("-", "_").lower() for p in parts)


def _generate_probe_cpp(
    vendor: str,
    family: str,
    device: str,
    peripheral_ids: list[str],
    base_addr_ids: set[str],
    rcc_per_ids: set[str],
) -> str:
    """Render the probe.cpp body.

    For every peripheral, we reference ``<peri>::kBaseAddress`` —
    proves the namespace + base-address constexpr line exist.  For
    every peripheral that the synthesiser populated a ``per_rcc_map``
    entry for, we also reference ``<peri>::kGateModel`` — proves the
    typed gate-model enumerator was emitted.  Both references go
    through a ``constexpr`` aggregate so the compiler MUST evaluate
    them at compile time.
    """
    ns = _ns_name(vendor, family, device)
    lines: list[str] = [
        "// alloy-codegen compile-gate probe TU",
        f"// {vendor}/{family}/{device}",
        "//",
        "// Generated by scripts/run_compile_gate.py.  References every",
        "// peripheral's kBaseAddress + kGateModel to prove the emitted",
        "// trait surface is structurally well-formed.",
        "",
        '#include "peripheral_id.hpp"',
        '#include "peripheral_traits.h"',
        '#include "rcc_traits.hpp"',
        '#include "rcc_enable.hpp"',
        "",
        f"namespace probe = {ns};",
        "",
        "// Force every peripheral's kBaseAddress to be evaluated at",
        "// compile time.  Missing namespace / missing kBaseAddress",
        "// fails the build via name-resolution error.",
        "constexpr auto _probe_base_address_sum = (",
        "    static_cast<std::uintptr_t>(0)",
    ]
    for per_id in peripheral_ids:
        # Skip peripherals without a base address (some IRQ-only
        # synthetic peripherals like RP2040's ``spare_irq`` carry
        # no MMIO block — the trait struct exists but has no
        # ``kBaseAddress`` member).
        if per_id not in base_addr_ids:
            continue
        # Sanitise peripheral id to a valid C++ identifier.  The
        # emitter does the same: ``hdmi_cec`` → ``hdmi_cec`` (no
        # change here since YAML peripheral ids are already
        # snake_case_lowercase), but ``-`` would need replacing.
        cpp_id = per_id.replace("-", "_")
        lines.append(f"    + probe::{cpp_id}::kBaseAddress")
    lines.append(");")
    lines.append("")

    # static_assert that every peripheral with a gate has a valid
    # kGateModel enumerator.  Since GateModel is a closed enum, any
    # value would compile — but the *reference* to kGateModel only
    # compiles if the line was emitted.
    if rcc_per_ids:
        lines.append(
            "// Force every peripheral with a synthesised RCC entry to"
        )
        lines.append("// expose a typed kGateModel.  Missing line → compile fail.")
        for per_id in sorted(rcc_per_ids):
            cpp_id = per_id.replace("-", "_")
            lines.append(
                f"static_assert(probe::{cpp_id}::kGateModel == "
                f"probe::{cpp_id}::kGateModel, "
                f'"{per_id}: kGateModel missing or malformed");'
            )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Per-device compile driver
# ---------------------------------------------------------------------------


def _emit_device_artifacts(
    vendor: str, family: str, device: str, out_dir: Path
) -> None:
    """Re-emit every artifact for one device into ``out_dir``.

    Reuses the exact entry points the CLI wires up (so the gate
    matches what end-users would emit via ``alloy-codegen``).
    """
    canonical, synthesised = load_with_synthesis(
        vendor=vendor, family=family, device=device
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    for entry in _EMITTERS:
        text = entry.fn(canonical, synthesised)
        (out_dir / entry.filename).write_text(text)


def _ir_hash(vendor: str, family: str, device: str) -> str:
    """Best-effort hash of the canonical IR.  Used as a cache key
    so identical IR re-runs skip regeneration.
    """
    canonical, synthesised = load_with_synthesis(
        vendor=vendor, family=family, device=device
    )
    payload = {
        "vendor": vendor,
        "family": family,
        "device": device,
        "n_peripherals": len(canonical.peripherals),
        "n_rcc_entries": len(synthesised.per_rcc_map),
        "peripheral_ids": [p.id for p in canonical.peripherals],
    }
    raw = json.dumps(payload, sort_keys=True).encode()
    return hashlib.sha256(raw).hexdigest()[:16]


def _gate_one_device(
    vendor: str,
    family: str,
    device: str,
    cache_root: Path,
    clang: str,
    extra_includes: tuple[Path, ...] = (),
) -> GateResult:
    """Emit + compile one device.  Returns a GateResult.

    Caching: the emitted tree lives at
    ``<cache_root>/<ir_hash>/<vendor>/<family>/<device>/`` and is
    reused on subsequent runs if the IR hash is unchanged.
    """
    try:
        canonical, synthesised = load_with_synthesis(
            vendor=vendor, family=family, device=device
        )
    except Exception as exc:
        return GateResult(vendor, family, device, "skip", f"load failed: {exc}")

    ir_hash = _ir_hash(vendor, family, device)
    artifact_dir = cache_root / ir_hash / vendor / family / device

    if not (artifact_dir / "peripheral_traits.h").exists():
        try:
            _emit_device_artifacts(vendor, family, device, artifact_dir)
        except Exception as exc:
            return GateResult(
                vendor, family, device, "fail", f"emit failed: {exc}"
            )

    # Generate probe.cpp listing every peripheral.  Two pre-computed
    # sets:
    #   * ``base_addr_ids`` — peripherals with a real MMIO block
    #     (kBaseAddress emitted).  Some synthetic peripherals like
    #     RP2040 ``spare_irq`` are IRQ-only; their struct exists but
    #     has no kBaseAddress member.  Filter via ``per.base``.
    #   * ``rcc_per_ids``   — peripherals whose synthesiser ran and
    #     stamped an extra["gate_model"] (so kGateModel is emitted).
    peri_ids = [p.id for p in canonical.peripherals]
    base_addr_ids = {p.id for p in canonical.peripherals if p.base is not None}
    rcc_per_ids = {
        per_id
        for per_id, rcc in synthesised.per_rcc_map.items()
        if "gate_model" in rcc.extra
    }
    probe_src = _generate_probe_cpp(
        vendor, family, device, peri_ids, base_addr_ids, rcc_per_ids
    )
    probe_path = artifact_dir / "probe.cpp"
    probe_path.write_text(probe_src)

    # Compose clang invocation: -I points at the device's emitted
    # tree (so ``#include "peripheral_traits.h"`` resolves).
    cmd = [clang, *PROBE_CFLAGS, f"-I{artifact_dir}"]
    for extra in extra_includes:
        cmd.append(f"-I{extra}")
    cmd.append(str(probe_path))

    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=artifact_dir,
        )
    except FileNotFoundError:
        return GateResult(
            vendor, family, device, "skip",
            f"clang++ not found at {clang}",
        )

    if proc.returncode == 0:
        return GateResult(vendor, family, device, "pass")
    detail = proc.stderr.strip() or proc.stdout.strip()
    # Truncate huge error output so the matrix stays readable.
    if len(detail) > 500:
        detail = detail[:480] + "...<truncated>"
    return GateResult(vendor, family, device, "fail", detail)


# ---------------------------------------------------------------------------
# Top-level driver
# ---------------------------------------------------------------------------


def _enumerate_targets(
    filter_device: str | None,
) -> list[tuple[str, str, str]]:
    """Walk the device registry, optionally filtered by device id."""
    targets: list[tuple[str, str, str]] = []
    for (vendor, family), devices in DEVICE_REGISTRY.items():
        for device in devices:
            if filter_device is None or device == filter_device:
                targets.append((vendor, family, device))
    return targets


def _is_reference_fixture(triple: tuple[str, str, str]) -> bool:
    return triple in REFERENCE_FIXTURES


def _print_matrix(results: list[GateResult]) -> None:
    """Pretty-print the pass/fail matrix grouped by family."""
    by_family: dict[tuple[str, str], list[GateResult]] = {}
    for r in results:
        by_family.setdefault((r.vendor, r.family), []).append(r)

    icon = {"pass": "✅", "fail": "❌", "skip": "⏭"}
    for (vendor, family), rows in sorted(by_family.items()):
        passes = sum(1 for r in rows if r.status == "pass")
        fails = sum(1 for r in rows if r.status == "fail")
        skips = sum(1 for r in rows if r.status == "skip")
        print(f"\n{vendor}/{family}: {passes}✅ {fails}❌ {skips}⏭")
        for r in rows:
            tag = "[ref]" if _is_reference_fixture((r.vendor, r.family, r.device)) else "     "
            line = f"  {icon[r.status]} {tag} {r.device}"
            if r.status == "fail":
                first_line = r.detail.split("\n", 1)[0]
                line += f"  — {first_line[:80]}"
            print(line)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Per-device compile gate for alloy-codegen v2.1 output."
    )
    parser.add_argument("--device", help="Restrict to a single device id")
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Parallel + fail-fast (for CI use)",
    )
    parser.add_argument(
        "--report-only",
        action="store_true",
        help="Print matrix and exit 0 even on failures",
    )
    parser.add_argument(
        "--reference-fixtures-only",
        action="store_true",
        help="Gate only the five GateModel reference fixtures",
    )
    parser.add_argument(
        "--clang",
        default=os.environ.get("CXX", "clang++"),
        help="clang++ binary (default: $CXX or clang++ on PATH)",
    )
    parser.add_argument(
        "--cache-root",
        default=str(REPO_ROOT / ".cache" / "compile-gate"),
        help="Where to keep regenerated artifact trees",
    )
    args = parser.parse_args(argv)

    cache_root = Path(args.cache_root)
    cache_root.mkdir(parents=True, exist_ok=True)

    targets = _enumerate_targets(args.device)
    if args.reference_fixtures_only:
        targets = [t for t in targets if _is_reference_fixture(t)]
    if not targets:
        print(f"no devices matched filter device={args.device!r}", file=sys.stderr)
        return 2

    print(
        f"compile-gate: {len(targets)} device(s), "
        f"clang={args.clang}, cache={cache_root}"
    )

    results: list[GateResult] = []

    if args.ci:
        max_workers = os.cpu_count() or 4
        with ThreadPoolExecutor(max_workers=max_workers) as pool:
            futures = {
                pool.submit(
                    _gate_one_device, v, f, d, cache_root, args.clang
                ): (v, f, d)
                for (v, f, d) in targets
            }
            for fut in as_completed(futures):
                r = fut.result()
                results.append(r)
                icon = {"pass": "✅", "fail": "❌", "skip": "⏭"}[r.status]
                print(f"  {icon} {r.triple}")
                if r.status == "fail" and not args.report_only:
                    # In CI mode, fail fast on the first hard-fail.
                    if _is_reference_fixture((r.vendor, r.family, r.device)):
                        for f2 in futures:
                            f2.cancel()
                        break
    else:
        for (v, f, d) in targets:
            r = _gate_one_device(v, f, d, cache_root, args.clang)
            results.append(r)
            icon = {"pass": "✅", "fail": "❌", "skip": "⏭"}[r.status]
            print(f"  {icon} {r.triple}")

    _print_matrix(results)

    # Exit code: zero if every reference fixture passed (and we're
    # not in --report-only mode that masks even ref-fixture fails).
    hard_failures = [
        r for r in results
        if r.status == "fail"
        and _is_reference_fixture((r.vendor, r.family, r.device))
    ]
    soft_failures = [
        r for r in results
        if r.status == "fail"
        and not _is_reference_fixture((r.vendor, r.family, r.device))
    ]
    print(
        f"\nsummary: {len(results)} total, "
        f"{sum(1 for r in results if r.status == 'pass')} pass, "
        f"{len(hard_failures)} hard-fail (reference fixtures), "
        f"{len(soft_failures)} soft-fail (report-only)"
    )

    if args.report_only:
        return 0
    return 1 if hard_failures else 0


if __name__ == "__main__":
    sys.exit(main())
